package lexicocode;

public enum TokenType {
    CLASS, INT, STRING, FLOAT,
    IF, ELSE, DO, WHILE, REPEAT, UNTIL,
    READ, WRITE, AND, OR, NOT,
    IDENTIFIER, INTEGER_CONST, REAL_CONST, STRING_LITERAL,
    ASSIGN, PLUS, MINUS, TIMES, DIVIDE, MOD,
    GT, GE, LT, LE, NE, EQ,
    LPAREN, RPAREN, LBRACE, RBRACE,
    COMMA, SEMICOLON,
    EOF
}

